logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: Inventory-service
          uri: http://localhost:8083/
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8080/
          predicates:
            - Path=/order/**
        - id: Account-service
          uri: http://localhost:8081/
          predicates:
            - Path=/account/**