logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: Inventory-service
          uri: http://localhost:8083/
          predicates:
            - Path=/inventory/**
          filters:
            filters:
              - AddRequestHeader=first-request, first-request-header
              - AddResponseHeader=first-response, first-response-header
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<segment>/?.*), $\{segment}
        - id: Account-service
          uri: lb://Account-service
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account(?<segment>/?.*), $\{segment}

